# Generated by Django 5.0.3 on 2024-05-19 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('ISBN', models.CharField(max_length=13)),
                ('year', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('dimensions', models.CharField(max_length=100)),
                ('cover', models.CharField(choices=[('H', 'Hardcover'), ('P', 'Paperback')], max_length=1)),
                ('category', models.CharField(choices=[('F', 'Fiction'), ('NF', 'Non-Fiction'), ('B', 'Biography'), ('C', 'Children')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.distributorhouse')),
            ],
        ),
    ]
