# Generated by Django 5.0.3 on 2024-03-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audapp', '0002_song_ep_album_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
