# Generated by Django 4.1 on 2024-06-06 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=50)),
                ('label_country', models.CharField(max_length=50)),
                ('label_city', models.CharField(max_length=50)),
                ('label_year', models.IntegerField()),
                ('label_website', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=50)),
                ('book_image', models.CharField(max_length=300)),
                ('book_isbn', models.CharField(max_length=100)),
                ('book_year', models.IntegerField()),
                ('book_cover', models.CharField(choices=[('soft cover', 'Soft Cover'), ('hard cover', 'Hard Cover')], max_length=15)),
                ('book_category', models.CharField(choices=[('romance', 'Romance'), ('thriller', 'Thriller'), ('biography', 'Biography'), ('classic', 'Classic'), ('drama', 'Drama'), ('history', 'History')], max_length=50)),
                ('book_price', models.IntegerField()),
                ('book_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knigi.recordlabel')),
            ],
        ),
    ]
