version: '3'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - TZ=UTC
    networks:
      - jenkins_network

networks:
  jenkins_network:

volumes:
  jenkins_home: