# Generated by Django 4.1 on 2024-06-06 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=50)),
                ('manufacturer_location', models.CharField(max_length=50)),
                ('manufacturer_year', models.IntegerField()),
                ('number_of_employees', models.IntegerField()),
                ('manufacturer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_price', models.IntegerField()),
                ('car_chassis', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_color', models.CharField(max_length=20)),
                ('car_year', models.IntegerField()),
                ('car_mileage', models.IntegerField()),
                ('car_type', models.CharField(choices=[('Sedan', 'sedan'), ('SUV', 'suv'), ('Hatchback', 'hatchback'), ('Coupe', 'Coupe')], max_length=50)),
                ('car_image', models.CharField(max_length=200)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avtomobili.manufacturer')),
            ],
        ),
    ]
