# Generated by Django 4.1 on 2024-06-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplement_name', models.CharField(max_length=100)),
                ('supplement_image', models.CharField(max_length=250)),
                ('supplement_code', models.CharField(max_length=300)),
                ('supplement_manufacturer', models.CharField(max_length=50)),
                ('is_available', models.BooleanField()),
                ('supplement_price', models.IntegerField()),
                ('supplement_category', models.CharField(choices=[('proteins', 'Proteins'), ('vitamins', 'Vitamins'), ('creatine', 'Creatine'), ('amino acids', 'Amino Acids'), ('pre-workout', 'Pre-Workout')], max_length=50)),
            ],
        ),
    ]
