# Generated by Django 4.1 on 2024-06-06 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('category_description', models.CharField(max_length=200)),
                ('category_created_date', models.DateTimeField()),
                ('is_real_estate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_title', models.CharField(max_length=100)),
                ('listing_description', models.CharField(max_length=200)),
                ('listing_date', models.DateTimeField()),
                ('listing_image', models.CharField(max_length=300)),
                ('listing_price', models.IntegerField()),
                ('listing_status', models.CharField(choices=[('fiksna', 'Cenata e fiksna'), ('predlozi', 'Prifakjam predlozi'), ('ne e fiksna', 'Cenata ne e fiksna')], max_length=50)),
                ('is_new', models.BooleanField(default=False)),
                ('listing_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oglasi.category')),
                ('listing_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
