# Generated by Django 5.0.3 on 2024-06-07 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('opis', models.CharField(max_length=100)),
                ('datum', models.DateField()),
                ('nedvizna', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Oglas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('opis', models.CharField(max_length=100)),
                ('vreme', models.TimeField()),
                ('datum', models.DateField()),
                ('image', models.ImageField(upload_to='data/')),
                ('cena', models.IntegerField()),
                ('status', models.CharField(choices=[('FIKSNA', 'FIKSNA'), ('PRIFAKJAM PREDLOZI', 'PRIFAKJAM PREDLOZI'), ('NE FIKSNA', 'NE FIKSNA')], max_length=100)),
                ('nov', models.BooleanField(default=False)),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kategorija')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
